### ISSUE TITLE
Create a landing page + SEO

### ISSUE THREAD

**Issue by aksiksi** [aksiksi/vaulty#23]
A custom landing page should be fine. Spin something up in Flask/Sanic.

All it will do is POST emails to the DB to build up a mailing list.

Actually, will be implementing this using Django.

## TODO

* [x] Get a basic Django app up and running.
* [x] Design a basic landing page using Bulma.
* [x] Write basic landing page email form.
* [x] Port all SQL models to Django ORM.  Preserve table names!
* [x] Add a new model for landing page signup form.
* [x] Write a simple Django view that takes user email, stores it in DB, then asks user to verify their email.  Once verified, email will get active flag set to `True`.
* [x] Create a basic Gunicorn systemd unit for socket and server
* [x] Prepare Nginx config file
* [x] Deploy the app with Gunicorn + Nginx: https://docs.gunicorn.org/en/stable/deploy.html
* [x] Customize Bulma with unique theme colors  (**deferred**)
* [x] Use Django to package all static resources on deploy
* [x] Create a custom User model: https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#substituting-a-custom-user-model
* [x] Get models into Django admin for easier add/delete/update of info
* [x] Get basic FAQ page
* [x] Send confirmation email once user signs up for mailing list.  See [here](https://docs.djangoproject.com/en/3.0/topics/email/) for details on which settings are required for mail.
* [x] Enforce unique constraint on launch list signup; see [this](https://stackoverflow.com/a/40866717) and [this](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#get-or-create)
* [x] Basic about page
* [x] Basic privacy policy

## Resources

* Basic homepage Semantic UI template: https://github.com/semantic-ui-forest/forest-templates/tree/master/semantic-ui/homepage
* Customize Bulma: https://bulma.io/documentation/customize/with-node-sass/
* https://github.com/timonweb/django-bulma
