### ISSUE TITLE
Implement GDrive storage backend 

### ISSUE THREAD

**Issue by aksiksi** [aksiksi/vaulty#28]
## Links

* API docs: https://developers.google.com/drive/api/v3/quickstart/js?authuser=1
* Resumable file upload: https://developers.google.com/drive/api/v3/quickstart/js?authuser=1
* OAuth2 tips: https://developers.google.com/identity/protocols/OAuth2WebServer

## Notes

* Unlike Dropbox, GDrive has no concept of a "path".  No names are unique.  Instead, must use ID to identify folders and files.
* For our use-case, we will need user to select storage folder via GDrive picker.  We will store its ID and upload stuff there.

## Endpoints

File upload/create: https://developers.google.com/drive/api/v3/reference/files/create

Example curl request to upload file to a folder (two steps):

```
$ curl -i --request POST "https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&key=YOUR_KEY" --header 'Content-Type: application/json' --header 'Authorization: Bearer YOUR_TOKEN' --data '{"name": "hello.txt", "parents": ["0B9bIgbhJcgN1VkhESjRqR1F4Q3c"]}'

HEADERS:
location: LOCATION_URL
```

```
$ curl -i --request PUT "LOCATION_URL" -H "Content-Type: text/plain" -H "Content-Length: 14" --data-binary "@/home/work/Downloads/hello.txt"
RETURNS:
{
 "kind": "drive#file",
 "id": "167IzkdvqywxEfbU_b6wwQJ1ErNCe4rsm",
 "name": "hello.txt",
 "mimeType": "text/plain"
}
```

## TODO

- [x] Create app client key
- [x] Create API key (for testing)
- [x] Test file uploading (resumable)
- [x] Use folder ID as storage path and set file parents on create 
- [ ] Overload storage path in DB with folder ID (hardcode for now)
- [ ] Write a basic two-step file upload API
- [ ] Add `api_key` column in DB (optional for GDrive, used for tracking)

Related to #17.
