### ISSUE TITLE
Enable TLS for filter, server, and DB

### ISSUE THREAD

**Issue by aksiksi** [aksiksi/vaulty#36]
This is a tracking issue for TLS support between filter, server, and DB.  

With commit aaa0f49aa042f71e291bedb92b0a7cc89bc88224 (reverted), we switched on TLS between filter and server, but this will cause difficulties since server runs as `vmail` user, which is not root.  However, LE certs are grabbed w/ root user.

## TODO

- [ ] Add support for TLS between filter and server (see aaa0f49aa042f71e291bedb92b0a7cc89bc88224 for diff).
- [ ] Evaluate overhead of enabling TLS between the two
- [ ] Evaluate whether or not it even makes sense, as both are running inside cloud provider network
- [ ] Enable TLS for DB (Postgress config, sqlx, Django)
